services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:7244
      - "8000:80"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library